### ISSUE TITLE
Dashboard authentication

### ISSUE THREAD

**Issue by jkomyno** [mmazzarolo/numvalidate#1] opened 2017-10-05 08:37 UTC
After having logged in the first time (using GitHub provider) I received an error that said that I "wasn't authorized to access the Dashboard". I've refreshed the page and everything worked as expected.

Expected behaviour: it should grant me access to the dashboard immediately after having logged in

**Comment by mmazzarolo** [comment] 2017-10-05 08:42
Hello @jkomyno , thank you for submitting the first issue 🤴 
I was taking a look at the issue on Sentry, and I'm 90% sure that it is caused by a delay on Auth0 side (I already experienced something like this in the past, randomly).  
This evening I'll try to report it to the Auth0 team... even if it's not super easy to reproduce.  
Anyway, a workaround I'd like to implement is [delaying this initialization](https://github.com/mmazzarolo/numvalidate/blob/master/client/pages/Dashboard.js#L62) to give time to process the "signup" to Auth0.

**Comment by jkomyno** [comment] 2017-10-05 08:50
@mmazzarolo, it's always nice to help somebody that lives nearby!

Is transitioning the login stack to Firebase or to Passport Oauth (so you have a deeper control) an option?

**Comment by jkomyno** [comment] 2017-10-05 08:51
Btw, if it can help, I'm using Chrome 61.0.3163.100 on Mac OS Sierra

**Comment by mmazzarolo** [comment] 2017-10-05 09:03
> @mmazzarolo, it's always nice to help somebody that lives nearby!  

Thanks man! I'm glad someone is already trying this project, I still haven't release it "officially", because I'd like to extensively document it in the README.md first and test it a bit more (I just published the app 12 hours ago).  
Btw... how did you find it? 🤔 

> Is transitioning the login stack to Firebase or to Passport Oauth (so you have a deeper control) an option?  

From a pure technical side, yes, it is.  
From a practical standpoint though, this would mean migrating the (really small) userbase currently registered in Auth0 (and I'm sure it won't be painless) and moving to probably higher costs.  

> Btw, if it can help, I'm using Chrome 61.0.3163.100 on Mac OS Sierra  

Thanks.  
I'd like to be as much open as possible though: I already logged this info through Sentry (which collects details when the status code is `> 400`):
<img width="1406" alt="schermata 2017-10-05 alle 10 57 11" src="https://user-images.githubusercontent.com/9536354/31219047-69a1b888-a9bc-11e7-9e35-e4e484a42bcc.png">

**Comment by jkomyno** [comment] 2017-10-05 09:23
I simply found your repo in my Github feed lol
![schermata 2017-10-05 alle 11 23 09](https://user-images.githubusercontent.com/12381818/31220052-7e666ab8-a9bf-11e7-88d3-765253299f5c.png)

**Comment by mmazzarolo** [comment] 2017-10-05 09:25
Between Dan and Brent, what an honour, hahaha 😸

**Comment by mmazzarolo** [comment] 2017-10-05 19:17
Should be fixed now 👍

**Closed by mmazzarolo** 2017-10-05 19:17 UTC
Labels: bug

**Comment by jkomyno** [comment] 2017-10-05 19:20
I'll try tomorrow morning!
